resources:
  repositories:
    - repository: Templates
      type: git
      name: AutomatizaceTestu

name: StavProstredi__$(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Year:yy).$(Month).$(DayOfMonth)

schedules:
- cron: '0 * * * *'
  displayName: Stav prostredi kazdu hodinu
  branches:
    include:
    - main
  always: true

trigger: none
#- main

stages: 
  - stage: Check_VPN_Status
    jobs:
    - job: cheackVpnStatus
      pool:
        name: "GDBuildSrv"
      steps:
        - checkout: none
          fetchDepth: 1
        - template: CheckVpnStatus.yml

  - stage: StavProstredi
    dependsOn: Check_VPN_Status
    jobs:
    - job: TestLogin
      pool:
        name: "GDBuildSrv"
      steps:
        - checkout: self
          fetchDepth: 1
        - template: RunSingleTest.yml
          parameters:
            TestFile: 'Tests/TestLogin.robot'
            TestName: 'TestLogin'

