resources:
  repositories:
    - repository: Templates
      type: git
      name: AutomatizaceTestu

name: TestZalozeniVytvoreniPocinu__$(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Year:yy).$(Month).$(DayOfMonth)

trigger: none
#- main

stages: 
  - stage: Check_VPN_Status
    jobs:
    - job: cheackVpnStatus
      pool:
        name: "GDBuildSrv"
      steps:
        - checkout: none
          fetchDepth: 1
        - template: CheckVpnStatus.yml

  - stage: TestZalozeniVytvoreniPocinu
    dependsOn: Check_VPN_Status
    jobs:
    - job: TestZalozeniVytvoreniPocinu
      pool:
        name: "GDBuildSrv"
      steps:
        - checkout: self
          fetchDepth: 1
        - template: RunSingleTest.yml
          parameters:
            TestFile: 'Tests/TestZalozeniAVytvoreniPocinu.robot'
            TestName: 'TestZalozeniAVytvoreniPocinu'

